### PR TITLE
Add support for links that aren't active elements (upstream)

### PR DESCRIPTION
**Pull request by nbolton**
In some apps, like Jira, the right-clicked link isn't always the active element.

This PR adds support for copying the text of links that are not active elements. The changes ensure that the link text can be copied via the context menu, even if the link is inside ShadowDOM. Additionally, the code has been refactored to improve readability and maintainability.

### CODE REVIEW

**Review by tophf — CHANGES_REQUESTED** [review]
Thanks, but I can't accept this, I've commented in https://github.com/tophf/copy-link-text/pull/2#issuecomment-2144900219

**Comment by nbolton** [comment]
> Thanks, but I can't accept this, I've commented in [#2 (comment)](https://github.com/tophf/copy-link-text/pull/2#issuecomment-2144900219)

Not a problem :)

I will not submit further PRs and will continue enhancing this extension on my own fork.

**Comment by nbolton** [comment]
Rejected by maintainer.

**Comment by nbolton** [comment]
> It already works for me. Can you show a site/demo where it doesn't?

The extension doesn't work in Jira, and other apps where the right-clicked element is not active.

> Is there a public demo? Right-clicking in my tests always makes the element active.

Did you try this in Jira? Try the issue preview overlay, it focuses the body of the issue instead of the clicked link.

image

**Comment by nbolton** [comment]
> Is there a public site with Jira?

I don't know, sorry. Maybe they have a free trial or a preview?

https://www.atlassian.com/software/jira

**Comment by tophf** [comment]
> Oh, that's just Prettier's defaults, pretty standard.

It's subjective, not standard. Personally I follow the existing code style when I make a PR, even if I don't like it.

> The main refactor was mostly around creating functions, etc.

I didn't use functions because the code was trivial and global functions aren't getting garbage-collected. For more complex content scripts I use functions inside a global IIFE.

> The original code was pretty difficult to read, no offense intended.

You mean the two lines in while loop in content.js? Because the rest of the code was as basic as it gets.

> Logging is pretty typical in most code.

It may be necessary in complex code to collect logs from users or debug something, but I don't see the need here. I actually find the code unreadable because of the added logs.

**Comment by nbolton** [comment]
All fair points, thanks for your feedback. I hope you have a nice day.

**Pull request closed without merging**
