### PR TITLE
Add support for links that aren't active elements

### PR DESCRIPTION
**Pull request by nbolton**
Adds support for copying the text of links that are not active elements. The changes ensure that the link text can be copied via the context menu, even if the link is inside ShadowDOM. Additionally, the code has been refactored to improve readability and maintainability.

### CODE REVIEW

**Comment by nbolton** [comment]
Oops, this includes changes from README.md which you probably don't want, I'll raise another PR without that.

**Comment by tophf** [comment]
> ensure that the link text can be copied via the context menu

It already works for me. Can you show a site/demo where it doesn't?

> the code has been refactored to improve readability

There's no need for refactoring, changing the quotes, spaces around braces, console.log.

**Comment by tophf** [comment]
Also no need for messages, it only complicates things as currently every execution adds a new listener.

**Comment by tophf** [comment]
Is there a public demo? Right-clicking in my tests always makes the element active.

**Comment by nbolton** [comment]
Replied on newer PR: https://github.com/tophf/copy-link-text/pull/3#issuecomment-2144919368

**Pull request closed without merging**
